Aayam/Aayam/Controllers/MasterController.cs
using DAL.Repositories.Admin.Interface;
using DAL.Repositories.Admin.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.Master;

namespace Aayam.Controllers
{
    public class MasterController : Controller
    {
        private readonly IDMaster _idMaster;
        public MasterController()
        {
            _idMaster = new DMaster();
        }
        
        //---------------------------Stream Methods-----------------------------//
        public ActionResult StreamSelect()
        {
            ModelState.Clear();
            return View(_idMaster.StreamSelect());
        }
        public ActionResult StreamInsert()
        {
            return View();
        }
        [HttpPost]
        public ActionResult StreamInsert(Streams objStream)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_idMaster.StreamInsert(objStream))
                    {
                        ViewBag.Message =true;
                    }
                }

                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult StreamUpdate(int Id)
        {
          
            return View(_idMaster.StreamSelect().Find(str => str.StreamID == Id));

        }
        [HttpPost]
        public ActionResult StreamUpdate(int Id, Streams objStream)
        {
            try
            {
                if ( _idMaster.StreamUpdate(Id,objStream))
                {
                    ViewBag.message = true;  
                }
                return RedirectToAction("StreamSelect");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult StreamDelete(int Id)
        {
            try
            {
              
                if (_idMaster.StreamDelete(Id))
                {
                    ViewBag.message = true;

                }
                return RedirectToAction("StreamSelect");

            }
            catch
            {
                return View();
            }
        }

        //---------------------------Course Methods-----------------------------//
        public ActionResult CourseSelect()
        {
            ModelState.Clear();
            return View(_idMaster.CourseSelect());
        }
        public ActionResult CourseInsert()
        {
            ViewBag.Streams = _idMaster.StreamSelect();
            return View();
        }
        [HttpPost]
        public ActionResult CourseInsert(Course objCourse)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_idMaster.CourseInsert(objCourse))
                    {
                        ViewBag.Message =true;
                    }
                }
                ViewBag.Streams = _idMaster.StreamSelect();
                ModelState.Clear();
                return View();
               
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CourseUpdate(int Id)
        {
            ViewBag.Streams = _idMaster.StreamSelect();
            return View(_idMaster.CourseSelect().Find(str => str.CourseID == Id));
        }
        [HttpPost]
        public ActionResult CourseUpdate(int Id, Course objCourse)
        {
            try
            {
                if (_idMaster.CourseUpdate(Id, objCourse))
                {
                    ViewBag.message = true;
                }
                return RedirectToAction("CourseSelect");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CourseDelete(int Id)
        {
            try
            {
                if (_idMaster.CourseDelete(Id))
                {
                    ViewBag.message = true;
                }
                return RedirectToAction("CourseSelect");
            }
            catch
            {
                return View();
            }
        }  
  
    }
}

Aayam/Aayam/Views/Master/CourseInsert.cshtml
@model ViewModel.Master.Course


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Course</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("CourseSelect", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Course</h3>
                </div>
                <div class="panel-body">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            <div class="row">
                                @Html.LabelFor(model => model.CourseName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.CourseName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                @Html.LabelFor(model => model.StreamID, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.StreamID, (ViewBag.Streams as List<ViewModel.Master.Streams>).Select(x => new SelectListItem() { Text = x.StreamName, Value = x.StreamID.ToString() }), "--SELECT--", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                            @if (ViewBag.Message == true)
                            {
                                <div class="alert alert-success">
                                    <strong>Course has been added!</strong>
                                </div>
                            }
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aayam/Aayam/Views/Master/CourseSelect.cshtml
@model IEnumerable<ViewModel.Master.CourseViewModel>

@*<p>
        @Html.ActionLink("Create New", "CourseInsert")
    </p>*@
<div class="page ">
    <div class="page-header">
        <h1 class="page-title">Course</h1>
        <div class="page-header-actions">
            <a href="@Url.Action("CourseInsert", "Master")"><input type="button" value="Add Course" class="btn btn-primary" /></a>
        </div>
    </div>
    <div class="page-content">
        <!-- Panel Form Elements -->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Course List</h3>
            </div>
            <div class="panel-body container-fluid">

                <table class="table table-striped table-bordered table-hover" id="CourseTable">
                    <thead class="thead-default">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.CourseName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Stream)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CourseName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Stream)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "CourseUpdate", new { id = item.CourseID }) |
                                    @Html.ActionLink("Delete", "CourseDelete", new { id = item.CourseID }, new { onclick = "return confirm('Are you sure you wish to delete this Course?');" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#CourseTable').DataTable();
    });
</script>

Aayam/Aayam/Views/Master/CourseUpdate.cshtml
@model ViewModel.Master.CourseViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Course</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("CourseSelect", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Update Course</h3>
                </div>
                <div class="panel-body">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.CourseID)

                            <div class="row">
                                @Html.LabelFor(model => model.CourseName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.CourseName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row">
                                @Html.LabelFor(model => model.StreamID, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.DropDownListFor(model => model.StreamID, (ViewBag.Streams as List<ViewModel.Master.Streams>).Select(x => new SelectListItem() { Text = x.StreamName, Value = x.StreamID.ToString() }), "--SELECT--", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamID, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-primary"  />
                                </div>
                            </div>
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "CourseSelect")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aayam/Aayam/Views/Master/StreamInsert.cshtml
@model ViewModel.Master.Streams


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Streams</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("StreamSelect", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Add Stream</h3>
                </div>
                <div class="panel-body container-fluid">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)
                            <div class="row">
                                <div class="col-sm-2">
                                    @Html.LabelFor(model => model.StreamName, new { @class = "control-label" })
                                </div>
                                <div class="form-group col-sm-4">
                                    @Html.TextBoxFor(model => model.StreamName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="row example example-buttons">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </div>
                            @if (ViewBag.Message == true)
                            {
                                <div class="alert alert-success">
                                    <strong>Stream has been added!</strong>
                                </div>
                            }
                        </div>
                        <div class="clearfix hidden-xs">
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
}



@*<div>
        @Html.ActionLink("Back to List", "StreamSelect")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Aayam/Aayam/Views/Master/StreamSelect.cshtml
@model IEnumerable<ViewModel.Master.Streams>



<div class="page ">
    <div class="page-header">
        <h1 class="page-title">Stream</h1>
        <div class="page-header-actions">
            <a href="@Url.Action("StreamInsert", "Master")"><input type="button" value="Add Stream" class="btn btn-primary" /></a>
        </div>
    </div>
    <div class="page-content">
        <!-- Panel Form Elements -->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Stream List</h3>
            </div>
            <div class="panel-body container-fluid">

                <table class="table table-striped table-bordered table-hover" id="streamTable">
                    <thead class="thead-default">
                        <tr>
                            @*<th class="studentHeader">
        @Html.DisplayNameFor(model => model.StreamID)
    </th>*@
                            <th class="studentHeader">
                                @Html.DisplayNameFor(model => model.StreamName)
                            </th>
                            <th class="studentHeader">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                @*<td>
                            @Html.DisplayFor(modelItem => item.StreamID)
                        </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.StreamName)
                                </td>
                                <td>

                                    @Html.ActionLink("Edit", "StreamUpdate", new { id = item.StreamID }, new { @class = "btn-outline" }) |

                                    @*@Html.ActionLink("Delete", "StreamDelete", new { id = item.StreamID })*@
                                    @Html.ActionLink("Delete", "StreamDelete", new { id = item.StreamID }, new { onclick = "return confirm('Are you sure you wish to delete this Stream?');" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<script>
    $(document).ready(function () {
        $('#streamTable').DataTable();
    });
</script>

Aayam/Aayam/Views/Master/StreamUpdate.cshtml
@model ViewModel.Master.Streams


@using (Html.BeginForm("StreamUpdate", "Master", FormMethod.Post,
                                      new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="page">
        <div class="page-header">
            <h1 class="page-title">Streams</h1>
            <div class="page-header-actions">
                <a href="@Url.Action("StreamSelect", "Master")"><input type="button" value="Back to List" class="btn btn-primary" /></a>
            </div>
        </div>
        <div class="page-content">
            <!-- Panel Form Elements -->
            <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">Update Stream</h3>
                </div>
                <div class="panel-body container-fluid">
                    <div class="row row-lg">
                        <div class="col-sm-12">
                            <h4 class="example-title"></h4>
                            @Html.ValidationSummary(true)

                            <div class="row">
                                @Html.LabelFor(model => model.StreamName, new { @class = "control-label col-md-2" })
                                <div class="form-group col-md-4">
                                    @Html.TextBoxFor(model => model.StreamName, null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.StreamName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="row example example-buttons">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="btn btn-primary" />
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}